name: iOS build and test

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform:iOS Simulator, id:47418464-E067-4C59-A3AF-392072F480A2, OS:14.3, name:iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup CocoaPods
        run: |
          ls -al
          pod install --repo-update --clean-install
      - name: Build and Test
        run: |
          ls -al
          echo "destination=${destination}"
          xcodebuild clean test -workspace "currencyconvert.xcworkspace" -scheme "currencyconvert" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
