name: Swift iOS application
on: pull_request
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.4.1,name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup CocoaPods
        run: |
          ls -al
          pod install --repo-update --clean-install
      - name: Build and Test
        run: |
          ls -al
          echo "destination=${destination}"
          xcodebuild clean test -workspace "currencyconverter".xcworkspace -scheme "currencyconverter" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
