# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8', 'platform=iOS Simulator,OS=13.1,name=iPhone 9']
        scheme: ['currencyconverter']
        xcode: ['/Applications/Xcode_12.4.app/Contents/Developer']
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v1
      - name: Bundle Install
        run: bundle install
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}
      - name: Podfile Setup
        run: bundle exec pod install
        env: 
          DEVELOPER_DIR: ${{matrix.destination}}
      - name: Build and test
        run: bundle exec fastlane scan --destination "${destination}" --scheme "${scheme}"
        env:
          scheme: ${{matrix.scheme}}
          destination: ${{matrix.destingation}}
          DEVELOPER_DIR: ${{matrix.xcode}}
